:sparkles: add endpoint for user deletion and endpoint for username and password update
AsyncPlanningPoker/BrieflyPlanningPoker pull request #135
Opened 2022-10-27 20:29 UTC by thenriique

2022-11-07 05:27 UTC, lineconquista requested changes

2022-11-07 05:27 UTC, lineconquista commented on packages/api/src/routes/user.ts
> +  const token = req.body.token;
Fiz algumas alterações nesse método, acho que podemos trocar e deixar dessa forma:
```
  const email = req.query.user;
  const db = req.app.get('userDbStore');

  try {
    const dataUpdate: any = { updatedAt: new Date() };
    const oldPassword = req.body.oldPassword;
    const password = req.body.password;
    const name = req.body.name;

    if (password) {
      const passwordMatch = await crypt.compare(oldPassword, password);
      if (passwordMatch) {
        dataUpdate.password = await crypt.create(password);
      } else {
        throw new Unauthorized('The password did not match.');
      }
    }
    name ? (dataUpdate.name = name) : {};
    await db.updatePassByEmail(email, dataUpdate);
    return res.sendStatus(200);
  } catch (error: any) {
    next(error);
  }
```

O que alterei foi:

- Utilizei o email que é setado o middleware auth.handler, igual ao que expliquei anteriormente
- Não fazemos a chamada do findByEmail pois uma vez que o token foi enviado via authorization e cai nessa request, significa que ele está válido, se está válido o usuário está logado e existe no banco. Caso, em alguma situação muito aleatória, não esteja ai podemos vai cair na exception sem problema, pq realmente é uma exception.
- Como utilizamos o schema com os campos esperados, não precisamos retornar o 400, caso algum campo possua valor com outro tipo será retornado erro por lá, e se não tiver os campos necessários simplesmente retorna 200 mas sem realizar nenhuma operação.

2022-11-07 05:28 UTC, lineconquista commented
Oiee, caso vocês fiquem com alguma dúvida a respeito dos comentários podemos marcar de conversar!! 🙃

2022-11-18 01:13 UTC, thenriique commented
@lineconquista fizemos as correções pontuadas, se ainda for necessario outras modificações so dar um toque, blz?

2022-11-22 00:06 UTC, lineconquista approved these changes

2022-11-22 00:09 UTC, merged